# Generated by Django 5.2.4 on 2025-07-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id_operacao', models.IntegerField(primary_key=True, serialize=False)),
                ('parametros', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
