# Generated by Django 5.2.4 on 2025-07-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='id_operacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
