# Generated by Django 5.2.4 on 2025-07-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_alter_operacao_id_operacao'),
        ('usuarios', '0003_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='usuarios.usuario'),
        ),
    ]
